version: "3"
services: 
  spotify:
    restart: always
    container_name: spotify-location
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - core-network

networks:
  core-network: 
    external: true
